version: "1.0"

services:
    postgress:
        image: postgres:17.4
        container_name: postgres_db
        environment:
            POSTGRES_USER: sharawy
            POSTGRES_PASSWORD: sharawy19821982
            POSTGRES_DB: school
        ports:
            - "5432:5432"
        volumes:
            - postgres_data:/var/lib/postgresql/data

    app:
        build: .
        container_name: nextjs_app
        ports:
            - "3000:3000"
        environment:
            - DATABASE_URL: postgresql://sharawy:sharawy19821982@localhost:5432/school
        depends_on:
            - postgres

volumes:
    postgres_data:
